[project]
name = "bg-remove"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "onnxruntime>=1.23.2",
    "python-multipart>=0.0.20",
    "rembg>=2.0.68",
]
